---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  ansible-lint .
  yamllint .
platforms:
  - name: instance
    image: docker.io/pycontribs/ubuntu
    pre_build_image: true
    capabilities:
      - NET_ADMIN
provisioner:
  name: ansible
verifier:
  name: ansible
