#!/bin/bash

if [ -e /proc/sys/net/ipv4/conf/all/rp_filter ]
then
  for filter in /proc/sys/net/ipv4/conf/*/rp_filter
  do
    echo 1 > $filter
  done
fi

/sbin/iptables-restore < /etc/iptables/rules.v4
/sbin/ip6tables-restore < /etc/iptables/rules.v6
